# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "skyssolutions/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"
ignore_deps = ["github.com/coredns/coredns"]

# previous release
previous = "v1.9.4"

pre_release = false

preface = """
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
* Linux: 6.12.9
* runc: 1.2.4
* containerd: 2.0.2

Talos is built with Go 1.23.4.
"""

    [notes.kube-apiserver-authorization-config]
        title = "kube-apiserver Authorization Config"
        description = """\
When using `.cluster.apiServer.authorizationConfig` the user provided order for the authorizers is honoured and `Node` and `RBAC` authorizers are always added to the end if not explicitly specified.

Eg: If user provides only `Webhook` authorizer, the final order will be `Webhook`, `Node`, `RBAC`.

To provide a specific order for `Node` or `RBAC` explicitly, user can provide the authorizer in the order they want.

Eg:

```yaml
cluster:
  apiServer:
    authorizationConfig:
      - type: Node
        name: Node
      - type: Webhook
        name: Webhook
        webhook:
          connectionInfo:
            type: InClusterConfig
        ...
      - type: RBAC
        name: rbac
```

Usage of `authorization-mode` CLI argument will not support this form of customization.
"""

    [notes.auditd]
        title = "auditd"
        description = """\
Kernel parameter `talos.auditd.disabled=1` can be used to disable Talos built-in `auditd` service.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
