# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"
ignore_deps = ["github.com/coredns/coredns"]

# previous release
previous = "v1.9.3"

pre_release = false

preface = """
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
* Linux: 6.12.13
* Flannel: 0.26.4

Talos is built with Go 1.23.6.
"""

    [notes.ingress-firewall]
        title = "Ingress Firewall"
        description = """\
Talos Ingress Firewall now filters access to Kubernetes NodePort services correctly.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
